environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

deploy_script:
  - npm install -g gh-pages
  - npx gh-pages -d dist